package com.hrm.dao;
import com.hrm.config.DBConnection;
import com.hrm.model.Payroll;
import java.sql.*;import java.util.*;
public class PayrollDAO {
 public List<Payroll> findForHR(int year) throws SQLException {return query("SELECT p.payroll_id,p.employee_id,CONCAT('NV',LPAD(p.employee_id,4,'0')),e.full_name,p.pay_month,p.pay_year,p.base_salary,p.overtime_pay,p.bonus,p.deduction,p.net_salary,p.status FROM payrolls p JOIN employees e ON e.employee_id=p.employee_id WHERE (?=0 OR p.pay_year=?) ORDER BY p.employee_id,p.pay_month",year,false,0);}
 public List<Payroll> findMine(int employeeId,int year) throws SQLException{return query("SELECT p.payroll_id,p.employee_id,CONCAT('NV',LPAD(p.employee_id,4,'0')),e.full_name,p.pay_month,p.pay_year,p.base_salary,p.overtime_pay,p.bonus,p.deduction,p.net_salary,p.status FROM payrolls p JOIN employees e ON e.employee_id=p.employee_id WHERE p.employee_id=? AND p.pay_year>=YEAR(e.hire_date) AND (?=0 OR p.pay_year=?) AND p.status='SENT' ORDER BY p.pay_year DESC,p.pay_month DESC",year,true,employeeId);}
 public List<Payroll> history(String text,int year,int month,String status)throws SQLException{
  String q="SELECT p.payroll_id,p.employee_id,CONCAT('NV',LPAD(p.employee_id,4,'0')),e.full_name,p.pay_month,p.pay_year,p.base_salary,p.overtime_pay,p.bonus,p.deduction,p.net_salary,p.status FROM payrolls p JOIN employees e ON e.employee_id=p.employee_id WHERE (?=0 OR p.pay_year=?) AND (?='' OR CONCAT('NV',LPAD(p.employee_id,4,'0')) LIKE ? OR e.full_name LIKE ? OR e.email LIKE ?) AND (?=0 OR p.pay_month=?) AND (?='Tất cả' OR p.status=?) ORDER BY p.created_at DESC,p.payroll_id DESC";
  List<Payroll>a=new ArrayList<>();try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement(q)){int i=1;p.setInt(i++,year);p.setInt(i++,year);p.setString(i++,text);p.setString(i++,"%"+text+"%");p.setString(i++,"%"+text+"%");p.setString(i++,"%"+text+"%");p.setInt(i++,month);p.setInt(i++,month);p.setString(i++,status);p.setString(i++,status);try(ResultSet r=p.executeQuery()){while(r.next())a.add(map(r));}}return a;
 }
 private List<Payroll> query(String q,int year,boolean mine,int emp)throws SQLException{List<Payroll>a=new ArrayList<>();try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement(q)){if(mine){p.setInt(1,emp);p.setInt(2,year);p.setInt(3,year);}else{p.setInt(1,year);p.setInt(2,year);}try(ResultSet r=p.executeQuery()){while(r.next())a.add(map(r));}}return a;}
 private Payroll map(ResultSet r)throws SQLException{return new Payroll(r.getInt(1),r.getInt(2),r.getString(3),r.getString(4),r.getInt(5),r.getInt(6),r.getDouble(7),r.getDouble(8),r.getDouble(9),r.getDouble(10),r.getDouble(11),r.getString(12));}
 public void createDraft(int employeeId,int month,int year)throws SQLException{String q="INSERT INTO payrolls(employee_id,pay_month,pay_year,base_salary,overtime_pay,bonus,deduction,net_salary,status) SELECT e.employee_id,?,?,e.base_salary,COALESCE((SELECT SUM(o.hours*o.hourly_rate*o.multiplier) FROM overtime_records o WHERE o.employee_id=e.employee_id AND MONTH(o.work_date)=? AND YEAR(o.work_date)=?),0),COALESCE((SELECT SUM(r.amount) FROM rewards_disciplines r WHERE r.employee_id=e.employee_id AND r.type='REWARD' AND MONTH(r.record_date)=? AND YEAR(r.record_date)=?),0),COALESCE((SELECT SUM(r.amount) FROM rewards_disciplines r WHERE r.employee_id=e.employee_id AND r.type='DISCIPLINE' AND MONTH(r.record_date)=? AND YEAR(r.record_date)=?),0),e.base_salary+COALESCE((SELECT SUM(o.hours*o.hourly_rate*o.multiplier) FROM overtime_records o WHERE o.employee_id=e.employee_id AND MONTH(o.work_date)=? AND YEAR(o.work_date)=?),0)+COALESCE((SELECT SUM(r.amount) FROM rewards_disciplines r WHERE r.employee_id=e.employee_id AND r.type='REWARD' AND MONTH(r.record_date)=? AND YEAR(r.record_date)=?),0)-COALESCE((SELECT SUM(r.amount) FROM rewards_disciplines r WHERE r.employee_id=e.employee_id AND r.type='DISCIPLINE' AND MONTH(r.record_date)=? AND YEAR(r.record_date)=?),0),'DRAFT' FROM employees e WHERE e.employee_id=? AND e.status='ACTIVE' AND e.hire_date<=LAST_DAY(STR_TO_DATE(CONCAT(?,'-',?,'-01'),'%Y-%m-%d')) AND (e.resignation_date IS NULL OR e.resignation_date>=STR_TO_DATE(CONCAT(?,'-',?,'-01'),'%Y-%m-%d')) ON DUPLICATE KEY UPDATE base_salary=VALUES(base_salary),overtime_pay=VALUES(overtime_pay),bonus=VALUES(bonus),deduction=VALUES(deduction),net_salary=VALUES(net_salary),status='DRAFT'";try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement(q)){int i=1;p.setInt(i++,month);p.setInt(i++,year);p.setInt(i++,month);p.setInt(i++,year);p.setInt(i++,month);p.setInt(i++,year);p.setInt(i++,month);p.setInt(i++,year);p.setInt(i++,month);p.setInt(i++,year);p.setInt(i++,month);p.setInt(i++,year);p.setInt(i++,month);p.setInt(i++,year);p.setInt(i++,employeeId);p.setInt(i++,year);p.setInt(i++,month);p.setInt(i++,year);p.setInt(i++,month);if(p.executeUpdate()==0)throw new SQLException("Nhân viên không còn hoạt động hoặc không làm việc trong kỳ lương.");}}
 public void send(int payrollId,int employeeId)throws SQLException{String q="UPDATE payrolls SET status='SENT',sent_at=NOW() WHERE payroll_id=? AND employee_id=?";try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement(q)){p.setInt(1,payrollId);p.setInt(2,employeeId);if(p.executeUpdate()==0)throw new SQLException("Không thể gửi phiếu lương. Kiểm tra lại phiếu đã chọn.");}}
}
