<<<<<<< HEAD
db.url=jdbc:mysql://localhost:3306/hrm_enterprise_db?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
db.user=root
db.password=tuan1234
=======
db.url=jdbc:mysql://localhost:3306/hrm_enterprise_db
db.user=root
db.password=
>>>>>>> c888654e27fb43d1b0002d042a50270e736e50b5
